name: frust
description: A Tunedbass Coffee Shop
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  window_manager: ^0.3.5
  #google_fonts: ^4.0.4
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  dio: ^5.3.2
  another_flushbar: ^1.12.30
  device_info_plus: ^9.0.3
  hive: ^2.2.3
  hive_flutter:
  dart_jsonwebtoken: ^2.9.1
  url_launcher: ^6.1.14
  internet_connection_checker: ^1.0.0+1
  file_picker: ^5.5.0
  webview_flutter: ^4.2.4
  cloudinary: ^1.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geocode: ^1.0.3
  google_fonts: ^6.0.0
  package_info_plus: ^4.1.0
  flutter_downloader: ^1.11.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  awesome_bottom_bar: ^1.2.4
  line_icons: ^2.0.3
  bootstrap_icons: ^1.11.1
  font_awesome_flutter: ^10.5.0
  iconify_flutter: ^0.0.5
  flutter_staggered_grid_view: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:
  change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true
 
  assets:
    - assets/images/
    - assets/
    - assets/html/map.html
    - assets/css/
    - assets/css/colors.css
