name: lebzcafe
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons: ^1.0.5
  window_manager: ^0.3.5
  #google_fonts: ^4.0.4
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  dio: ^5.3.2
  another_flushbar: ^1.12.30
  device_info_plus: ^9.0.3
  hive: ^2.2.3
  hive_flutter: 
  dart_jsonwebtoken: ^2.9.1
  url_launcher: ^6.1.14
  internet_connection_checker: ^1.0.0+1
  file_picker: ^5.5.0
  cloudinary: ^1.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geocode: ^1.0.3
  google_fonts: ^6.0.0
  package_info_plus: ^4.1.0
  flutter_downloader: ^1.11.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^1.1.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  socket_io_client: ^2.0.3+1
  awesome_notifications: ^0.8.2
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  flutter_inappwebview: ^5.8.0
  flutter_hooks: ^0.20.3
  sliver_tools: ^0.2.12
  via_logger: ^1.0.4
  flutter_native_splash: ^2.3.6
  tu:
    path: /media/tonni/win/src/Mint/Documents/GitHub/flutter/tu/
  

flutter_native_splash:
  color: "#8C5F4D"
  image: "assets/images/splash.png"
  fullscreen: true

  android_12:
    icon_background_color: "#8C5F4D"
    color: "#8C5F4D"
    #image: "assets/images/splash_12.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  rename_app: ^1.3.1
  change_app_package_name: ^1.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/icons/
      - assets/
  