"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Review = exports.Store = exports.Cart = exports.User = exports.Order = exports.Product = void 0;
const product_1 = require("./product");
const mongoose_1 = require("mongoose");
const user_1 = require("./user");
const store_1 = require("./store");
const order_1 = require("./order");
const cart_1 = require("./cart");
const review_1 = require("./review");
const Product = (0, mongoose_1.model)("Product", product_1.ProductSchema);
exports.Product = Product;
const User = (0, mongoose_1.model)("User", user_1.UserSchema);
exports.User = User;
const Order = (0, mongoose_1.model)("Order", order_1.OrderSchema);
exports.Order = Order;
const Cart = (0, mongoose_1.model)("Cart", cart_1.CartSchema);
exports.Cart = Cart;
const Store = (0, mongoose_1.model)("Store", store_1.StoreSchema);
exports.Store = Store;
const Review = (0, mongoose_1.model)("Review", review_1.ReviewSchema);
exports.Review = Review;
